### ISSUE TITLE
v0.15.2 - panic: close of closed channel in peeble

### ISSUE THREAD

**Issue by matveynator** [chaisql/chai#507]
### What version of Genji are you using?

<pre>
v0.15.2
</pre>

### What did you do?

panic: close of closed channel [recovered]
	panic: close of closed channel

goroutine 6 [running]:
github.com/cockroachdb/pebble.Open.func1()
	/Users/matvey/sitebrush/vendor/github.com/cockroachdb/pebble/open.go:111 +0x175
panic({0x100be6e20, 0x100e7f370})
	/usr/local/go/src/runtime/panic.go:890 +0x262
github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).stopTicker(...)
	/Users/matvey/sitebrush/vendor/github.com/cockroachdb/pebble/vfs/disk_health.go:164
github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).Close(0xc00012c1e0)
	/Users/matvey/sitebrush/vendor/github.com/cockroachdb/pebble/vfs/disk_health.go:177 +0x25
github.com/cockroachdb/pebble.Open.func2()
	/Users/matvey/sitebrush/vendor/github.com/cockroachdb/pebble/open.go:165 +0x4b
github.com/cockroachdb/pebble.Open({0xc0000383a0, 0x1e}, 0xc000284240)
	/Users/matvey/sitebrush/vendor/github.com/cockroachdb/pebble/open.go:207 +0xe07
github.com/genjidb/genji/internal/database.OpenPebble({0xc0000383a0, 0x1e}, 0x0?, 0xc00006f740)
	/Users/matvey/sitebrush/vendor/github.com/genjidb/genji/internal/database/database.go:106 +0x1f7
github.com/genjidb/genji/internal/database.Open({0xc0000383a0, 0x1e}, 0x100b47b2e?)
	/Users/matvey/sitebrush/vendor/github.com/genjidb/genji/internal/database/database.go:79 +0x167
github.com/genjidb/genji.OpenWith({0xc0000383a0?, 0x0?}, 0x0?)
	/Users/matvey/sitebrush/vendor/github.com/genjidb/genji/db.go:53 +0x85
github.com/genjidb/genji.Open(...)
	/Users/matvey/sitebrush/vendor/github.com/genjidb/genji/db.go:35
github.com/genjidb/genji/driver.sqlDriver.OpenConnector({}, {0xc0000383a0?, 0x1015f0010?})
	/Users/matvey/sitebrush/vendor/github.com/genjidb/genji/driver/driver.go:36 +0x25
database/sql.Open({0x7ff7bfeffbc0, 0x5}, {0xc0000383a0, 0x1e})
	/usr/local/go/src/database/sql/sql.go:823 +0x109
sitebrush/pkg/database.connectToDb({{0x100d06cff, 0x9}, {0x0, 0x0}, {0xc00003c130, 0x9}, {0xc00003c100, 0xc}, {0xc00003c120, 0xe}, ...})
	/Users/matvey/sitebrush/pkg/database/functions.go:18 +0x7b
sitebrush/pkg/database.databaseWorkerRun(_, {{0x100d06cff, 0x9}, {0x0, 0x0}, {0xc00003c130, 0x9}, {0xc00003c100, 0xc}, {0xc00003c120, ...}, ...})
	/Users/matvey/sitebrush/pkg/database/database.go:54 +0xf8
created by sitebrush/pkg/database.Run.func1
	/Users/matvey/sitebrush/pkg/database/database.go:37 +0x28
exit status 2

**Comment by yaziine** [comment]
can you provide the steps to reproduce this please?

**Comment by asdine** [comment]
Closing this as we released v0.16.0. Please reopen if it happens again
